### ISSUE TITLE
NCC: UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by mcmarkj** [1Password/connect-sdk-js#23]
### Your environment
SDK Version: 1.0.0 or 1.0.1 - happening on both

OS: Ubuntu / MacOs

Node Version: v12.9.1

## What happened?
NCC is failing to compile the project complaining of a TypeError of type null. 

## What did you expect to happen?
The project should compile normally. 

## Steps to reproduce
1. Compile the project with ncc `ncc build`

## Notes & Logs
```
(node:64130) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of null
    at handleWrappers (/Users/markmcwhirter/Documents/personal/1password-actions/node_modules/@vercel/ncc/dist/ncc/loaders/relocate-loader.js.cache.js:12:121388)
    at e.exports (/Users/markmcwhirter/Documents/personal/1password-actions/node_modules/@vercel/ncc/dist/ncc/loaders/relocate-loader.js.cache.js:12:97983)
    at Object.e.exports (/Users/markmcwhirter/Documents/personal/1password-actions/node_modules/@vercel/ncc/dist/ncc/loaders/relocate-loader.js.cache.js:12:79903)
    at LOADER_EXECUTION (/Users/markmcwhirter/Documents/personal/1password-actions/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:879014)
    at runSyncOrAsync (/Users/markmcwhirter/Documents/personal/1password-actions/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:879025)
    at iterateNormalLoaders (/Users/markmcwhirter/Documents/personal/1password-actions/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:880623)
    at iterateNormalLoaders (/Users/markmcwhirter/Documents/personal/1password-actions/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:880491)
    at /Users/markmcwhirter/Documents/personal/1password-actions/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:880720
    at runSyncOrAsync (/Users/markmcwhirter/Documents/personal/1password-actions/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:879178)
    at iterateNormalLoaders (/Users/markmcwhirter/Documents/personal/1password-actions/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:880623)
(node:64130) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

I've created a separate Typscript project importing only 1Password's SDK and it's occurring there. This is happening on multiple machines, so I've ruled out an issue with my development environment. 
![image](https://user-images.githubusercontent.com/8041254/119648098-f2fb9a80-be18-11eb-8aed-b07b3e93c3ce.png)

**Comment by verkaufer** [comment]
Thanks for reporting! 

We'll take a look and see what's causing this issue. We haven't tested the module using [ncc](https://github.com/vercel/ncc) before, but we'll get back to you about that shortly.

**Comment by verkaufer** [comment]
I'm able to reproduce this issue, but I'm not sure where the issue could be coming from because stacktrace you posted point to ncc's `relocate-loader.js`. I'm not sure if the issue is from our package, our dependencies, or `ncc` itself.

I suggest opening an [issue](https://github.com/vercel/ncc/issues) in the `ncc` repository. You can reference our [dependency list ](https://www.npmjs.com/package/@1password/connect?activeTab=dependencies) if that helps them debug. 

We're happy to consider any changes the `ncc` folks suggest. 

Thanks again for reporting this issue and I appreciate your help getting to the bottom of it.
